"""Predeclared fictional answer-bearing passage challenge, not legal gold.

Calibrate one exploratory scalar cutoff on calibration rows ONLY, then freeze it
before evaluation. Neither partition may be used for training or promotion.
The target is whether a passage supplies the requested field/attributed statement,
not whether an event is true. Relevance scores are not entailment probabilities.
"""

# (ID, question, passage A, passage B, answer-bearing index or None)
CALIBRATION = (
    (
        "cal-01",
        "Which date does the depot slip give for collection?",
        "The depot slip was printed on May 21.",
        "Collection occurred on May 18 according to the depot slip.",
        1,
    ),
    (
        "cal-02",
        "Which date does the depot slip give for collection?",
        "The depot slip was printed on May 21.",
        "Collection was requested for May 18; the slip has no completed collection field.",
        None,
    ),
    (
        "cal-03",
        "What amount does the corrected worksheet list for transport?",
        "The correction lists transport at 46 dollars.",
        "The discarded transport estimate was 64 dollars.",
        0,
    ),
    (
        "cal-04",
        "What amount does the corrected worksheet list for transport?",
        "The note asks for a corrected transport figure.",
        "The only enclosed worksheet is marked superseded.",
        None,
    ),
    (
        "cal-05",
        "Who does the attendance note identify as accompanying Child K?",
        "Parent L accompanied Child M.",
        "The attendance note identifies Parent N as accompanying Child K.",
        1,
    ),
    (
        "cal-06",
        "Who does the attendance note identify as accompanying Child K?",
        "Parent L accompanied Child M.",
        "Child K's attendance row contains no companion name.",
        None,
    ),
    (
        "cal-07",
        "What time did the reply accept for the handover?",
        "The reply accepts the handover at four in the afternoon.",
        "The first email proposed a noon handover.",
        0,
    ),
    (
        "cal-08",
        "What time did the reply accept for the handover?",
        "The first email proposed a noon handover.",
        "The reply asks for more options and does not accept a time.",
        None,
    ),
    (
        "cal-09",
        "Which enclosure does the cover note identify as missing?",
        "The cover note identifies the bus invoice as missing.",
        "The meal receipt is attached to the cover note.",
        0,
    ),
    (
        "cal-10",
        "Which enclosure does the cover note identify as missing?",
        "The cover note lists several enclosures.",
        "No missing enclosure is named in the supplied cover note.",
        None,
    ),
    (
        "cal-11",
        "What did Parent P report about the unsigned calendar?",
        "The calendar has a blue border.",
        "Parent P reported receiving an unsigned calendar.",
        1,
    ),
    (
        "cal-12",
        "What did Parent P report about the unsigned calendar?",
        "Parent Q reported receiving an unsigned calendar.",
        "No statement by Parent P is included.",
        None,
    ),
    (
        "cal-13",
        "Which address was replaced by the correction slip?",
        "The correction replaces 12 Fictional Lane with 14 Fictional Lane.",
        "The envelope carries a green stamp.",
        0,
    ),
    (
        "cal-14",
        "Which address was replaced by the correction slip?",
        "A correction slip was requested.",
        "Neither the former nor replacement address appears in this record.",
        None,
    ),
    (
        "cal-15",
        "What document does the request ask to preserve?",
        "The directory was exported yesterday.",
        "The request asks to preserve the original appointment log.",
        1,
    ),
    (
        "cal-16",
        "What document does the request ask to preserve?",
        "The message announces a future preservation request.",
        "No document to preserve is identified.",
        None,
    ),
)

EVALUATION = (
    (
        "eval-01",
        "Find when the registry annotation was entered, not when its subject happened.",
        "The subject of the registry annotation happened on July 6.",
        "The annotation was entered in the registry on July 11.",
        1,
    ),
    (
        "eval-02",
        "Find when the registry annotation was entered, not when its subject happened.",
        "The subject of the registry annotation happened on July 6.",
        "The registry export bears a July 14 creation stamp but omits the annotation entry date.",
        None,
    ),
    (
        "eval-03",
        "Locate the final approved mileage figure rather than the amount first requested.",
        "The reviewer approved 29 dollars for mileage.",
        "The initial mileage request sought 92 dollars.",
        0,
    ),
    (
        "eval-04",
        "Locate the final approved mileage figure rather than the amount first requested.",
        "The initial mileage request sought 92 dollars.",
        "Approval of the mileage request is still pending.",
        None,
    ),
    (
        "eval-05",
        "Identify whose pickup was witnessed for Child R.",
        "The observer watched Parent T collect Child S.",
        "The observer watched Parent U collect Child R.",
        1,
    ),
    (
        "eval-06",
        "Identify whose pickup was witnessed for Child R.",
        "The observer watched Parent T collect Child S.",
        "Child R is mentioned only in an unconfirmed future pickup plan.",
        None,
    ),
    (
        "eval-07",
        "Locate the scheduling notice's replacement day after the postponement.",
        "The notice moves the session to Thursday.",
        "The obsolete invitation listed Monday.",
        0,
    ),
    (
        "eval-08",
        "Locate the scheduling notice's replacement day after the postponement.",
        "The notice postpones the session without a new day.",
        "The obsolete invitation listed Monday.",
        None,
    ),
    (
        "eval-09",
        "Which exact file does the delivery receipt say was delivered?",
        "The delivery receipt records delivery of the scanned consent sheet.",
        "An earlier request asked for a signed transport form.",
        0,
    ),
    (
        "eval-10",
        "Which exact file does the delivery receipt say was delivered?",
        "An earlier request asked for a signed transport form.",
        "The empty delivery template identifies no delivered file.",
        None,
    ),
    (
        "eval-11",
        "Locate the author's allegation, without treating it as a decision.",
        "The folder inventory lists an undated letter.",
        "The author alleges that the appointment notice was withheld.",
        1,
    ),
    (
        "eval-12",
        "Locate the author's allegation, without treating it as a decision.",
        "The folder inventory lists an undated letter.",
        "The letter's text is absent from the supplied materials.",
        None,
    ),
    (
        "eval-13",
        "Which page number did the errata sheet correct?",
        "The errata sheet changes the reference from page 17 to page 71.",
        "The cover was copied in grayscale.",
        0,
    ),
    (
        "eval-14",
        "Which page number did the errata sheet correct?",
        "The cover says an errata sheet should follow.",
        "No errata sheet or corrected page number was supplied.",
        None,
    ),
    (
        "eval-15",
        "Find the item the acknowledgment says was returned.",
        "The demand requested return of a notebook.",
        "The acknowledgment says the access badge was returned.",
        1,
    ),
    (
        "eval-16",
        "Find the item the acknowledgment says was returned.",
        "The demand requested return of a notebook.",
        "The unsigned acknowledgment template names no returned item.",
        None,
    ),
)
