"""Fresh fictional research challenge, declared before typed-field inference.

Not training material, legal gold or independent human evaluation. Expected spans
are reference annotations for supplied text, not adjudicated real-world facts.
"""

# ID, field type, basis, question, source text, expected exact substring or None.
CASES = (
    (
        "field-01",
        "clock_time",
        "reported_event",
        "At what time did the bus arrive?",
        "The fictional bus arrived at 08:35.",
        "08:35",
    ),
    (
        "field-02",
        "calendar_date",
        "reported_event",
        "On what date was the packet received?",
        "The fictional packet was received on April 14.",
        "April 14",
    ),
    (
        "field-03",
        "money",
        "reported_event",
        "What amount was paid?",
        "The fictional receipt states that 85 dollars was paid for supplies.",
        "85 dollars",
    ),
    (
        "field-04",
        "clock_time",
        "source_field",
        "What time is written beside the meeting?",
        "The fictional log lists the meeting time as 2:15 pm.",
        "2:15 pm",
    ),
    (
        "field-05",
        "calendar_date",
        "source_field",
        "What is the form's issue date?",
        "The fictional form has an issue date of June 21 and a due date of July 2.",
        "June 21",
    ),
    (
        "field-06",
        "money",
        "source_field",
        "What is the requested amount?",
        "The fictional request asks for 240 dollars. Only 160 dollars was approved.",
        "240 dollars",
    ),
    (
        "field-07",
        "clock_time",
        "reported_event",
        "When did the session begin?",
        "The fictional session was scheduled for 10:00 but began at 10:20.",
        "10:20",
    ),
    (
        "field-08",
        "calendar_date",
        "reported_event",
        "When did the actual delivery occur?",
        "The fictional delivery was planned for May 5. Delivery occurred on May 7.",
        "May 7",
    ),
    (
        "field-09",
        "clock_time",
        "reported_event",
        "When did the visitor arrive?",
        "The fictional visitor arrived at 16:40. The clerk recorded the arrival at 16:55.",
        "16:40",
    ),
    (
        "field-10",
        "calendar_date",
        "source_field",
        "What date was the arrival entered in the log?",
        "The fictional visitor arrived on August 3. "
        "The arrival was entered in the log on August 4.",
        "August 4",
    ),
    (
        "field-11",
        "money",
        "reported_event",
        "What amount was received?",
        "The fictional account received 55 dollars after requesting 70 dollars.",
        "55 dollars",
    ),
    (
        "field-12",
        "clock_time",
        "source_field",
        "What time was the appointment scheduled for?",
        "The fictional appointment was scheduled for 11:45. Attendance is not documented.",
        "11:45",
    ),
    (
        "field-13",
        "clock_time",
        "reported_event",
        "What time did the bus arrive?",
        "The fictional bus arrived on April 14. Its arrival time is not recorded.",
        None,
    ),
    (
        "field-14",
        "calendar_date",
        "reported_event",
        "On what date did the visitor arrive?",
        "The fictional visitor arrived at 08:35. No arrival date appears in the log.",
        None,
    ),
    (
        "field-15",
        "clock_time",
        "reported_event",
        "When did the appointment actually occur?",
        "The fictional appointment was scheduled for 11:45. Attendance is not documented.",
        None,
    ),
    (
        "field-16",
        "money",
        "reported_event",
        "What amount was actually paid?",
        "The fictional request asks for 240 dollars. No payment is recorded.",
        None,
    ),
    (
        "field-17",
        "clock_time",
        "reported_event",
        "What time did the handoff occur?",
        "A fictional witness claimed that the handoff occurred at 14:10. The claim is unverified.",
        None,
    ),
    (
        "field-18",
        "calendar_date",
        "reported_event",
        "When did the package arrive?",
        "The fictional package would have arrived on October 12 if shipment had occurred.",
        None,
    ),
    (
        "field-19",
        "money",
        "reported_event",
        "What amount was received?",
        "If the fictional request succeeds, 95 dollars could be received.",
        None,
    ),
    (
        "field-20",
        "clock_time",
        "reported_event",
        "What time did the meeting end?",
        "The fictional meeting began at 13:05. The end time is unknown.",
        None,
    ),
    (
        "field-21",
        "calendar_date",
        "source_field",
        "What date did the second packet arrive?",
        "The first fictional packet arrived on September 8. "
        "A second packet appears only on an inventory.",
        None,
    ),
    (
        "field-22",
        "money",
        "source_field",
        "What was the refund amount?",
        "The fictional receipt lists a purchase of 65 dollars and a delivery charge of 2 dollars.",
        None,
    ),
    (
        "field-23",
        "clock_time",
        "reported_event",
        "What time did the pickup occur?",
        "The first fictional log says pickup occurred at 15:20. "
        "A second log says 16:05. The discrepancy is unresolved.",
        None,
    ),
    (
        "field-24",
        "calendar_date",
        "source_field",
        "What date is on the missing page?",
        "The fictional cover page is dated November 17. "
        "An index gives the requested page number as five.",
        None,
    ),
)
