"""Fresh pre-inference clause challenge; fictional, not training or human gold."""

CASES = (
    (
        "clause-01",
        "clock_time",
        "reported_event",
        "When did the seminar begin?",
        "The fictional seminar was scheduled for 09:00 but began at 09:25.",
        "09:25",
    ),
    (
        "clause-02",
        "calendar_date",
        "reported_event",
        "When did the parcel arrive?",
        "The fictional parcel was planned for June 2. It arrived on June 4.",
        "June 4",
    ),
    (
        "clause-03",
        "money",
        "reported_event",
        "How much was received?",
        "The fictional request was for 180 dollars but 125 dollars was received.",
        "125 dollars",
    ),
    (
        "clause-04",
        "clock_time",
        "source_field",
        "What time was the consultation scheduled for?",
        "The fictional consultation was scheduled for 14:30. Attendance is not recorded.",
        "14:30",
    ),
    (
        "clause-05",
        "clock_time",
        "reported_event",
        "When did the visitor arrive?",
        "The fictional visitor arrived at 07:50. The departure time is unknown.",
        "07:50",
    ),
    (
        "clause-06",
        "calendar_date",
        "source_field",
        "When was the receipt entered?",
        "The fictional parcel arrived on December 2. The receipt was entered on December 3.",
        "December 3",
    ),
    (
        "clause-07",
        "money",
        "source_field",
        "What amount was requested?",
        "The fictional request lists 330 dollars. A payment date is missing.",
        "330 dollars",
    ),
    (
        "clause-08",
        "clock_time",
        "reported_event",
        "When did the session end?",
        "The fictional session ended at 17:15. Another session was proposed for 18:00.",
        "17:15",
    ),
    (
        "clause-09",
        "calendar_date",
        "reported_event",
        "When was the notice delivered?",
        "The fictional notice was delivered on February 19; "
        "a follow-up was planned for February 23.",
        "February 19",
    ),
    (
        "clause-10",
        "clock_time",
        "source_field",
        "What meeting time is listed?",
        "The fictional log lists the meeting time as 15:40.",
        "15:40",
    ),
    (
        "clause-11",
        "money",
        "reported_event",
        "How much was paid?",
        "The fictional receipt states that 92 dollars was paid for paper.",
        "92 dollars",
    ),
    (
        "clause-12",
        "calendar_date",
        "source_field",
        "What is the notice date?",
        "The fictional notice date is January 22. The date of mailing is blank.",
        "January 22",
    ),
    (
        "clause-13",
        "clock_time",
        "reported_event",
        "When did the seminar actually begin?",
        "The fictional seminar was scheduled for 09:00. A printed cover says 09:25.",
        None,
    ),
    (
        "clause-14",
        "clock_time",
        "reported_event",
        "When did the seminar actually begin?",
        "The fictional seminar was scheduled for 09:00 but its actual start is unknown.",
        None,
    ),
    (
        "clause-15",
        "calendar_date",
        "reported_event",
        "When did the parcel arrive?",
        "The fictional statement is unverified. It says the parcel arrived on June 4.",
        None,
    ),
    (
        "clause-16",
        "clock_time",
        "reported_event",
        "When did the visitor arrive?",
        "The following fictional account is conditional. The visitor arrived at 07:50.",
        None,
    ),
    (
        "clause-17",
        "money",
        "reported_event",
        "How much was paid?",
        "The fictional note says 92 dollars was paid. That statement is not correct.",
        None,
    ),
    (
        "clause-18",
        "calendar_date",
        "reported_event",
        "When did the notice arrive?",
        "The first fictional note says the notice arrived on February 19. "
        "A conflicting note says February 20.",
        None,
    ),
    (
        "clause-19",
        "clock_time",
        "reported_event",
        "When did the visitor arrive?",
        "The fictional visitor did not arrive at 07:50. A planned meeting began at 08:10.",
        None,
    ),
    (
        "clause-20",
        "calendar_date",
        "source_field",
        "What is the mailing date?",
        "The fictional mailing field contains 03/04. The format is unspecified.",
        None,
    ),
    (
        "clause-21",
        "clock_time",
        "reported_event",
        "When did Visitor Alder arrive?",
        "Visitor Birch arrived at 10:45. "
        "Visitor Alder is named in the fictional attendance directory.",
        None,
    ),
    (
        "clause-22",
        "money",
        "reported_event",
        "How much was paid?",
        "The fictional applicant requested 220 dollars. A letter proposed approval of 150 dollars.",
        None,
    ),
    (
        "clause-23",
        "clock_time",
        "source_field",
        "What is the departure time?",
        "The fictional log gives arrival as January 22. The departure column is empty.",
        None,
    ),
    (
        "clause-24",
        "calendar_date",
        "reported_event",
        "When did the delivery occur?",
        "The fictional delivery occurred on August 16, according to an allegation. "
        "The account is disputed.",
        None,
    ),
)
