import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(process.env.MFL_PROOF_NODE_MODULES,'playwright'));
const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
assert.equal(new URL(input.base_url).hostname,'127.0.0.1');
assert.ok(!fs.existsSync(input.output));
const report={fictional_only:true,model_inference:false,frozen_app:false,page_errors:[],external_requests:[],checks:[]};
let browser,page;
const started=performance.now();
function check(name){report.checks.push(name);fs.writeFileSync(input.output.replace('.json','.progress.json'),JSON.stringify(report,null,2));}
const watchdog=setTimeout(()=>{report.deadline_exceeded=true;if(browser)void browser.close().catch(()=>{});},80000);
try{
  browser=await chromium.launch({channel:'msedge',headless:true,env:{...process.env,APPDATA:process.env.TEMP,LOCALAPPDATA:process.env.TEMP},args:['--disable-background-networking','--disable-component-update']});
  report.browser_version=browser.version();
  const context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});
  await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==input.base_url){report.external_requests.push(route.request().url());return route.abort();}return route.continue();});
  await context.addInitScript(()=>{localStorage.setItem('mfl-onboarding-complete','true');sessionStorage.setItem('mfl_local_capability_session_v1','a'.repeat(48));});
  page=await context.newPage();page.on('pageerror',error=>report.page_errors.push(error.message));
  await page.goto(input.base_url,{waitUntil:'networkidle'});
  assert.equal(await page.locator('body').getAttribute('data-production-ui'),'workbench');
  await page.locator('#v8-view-menu summary').click();
  await page.locator('[data-v8-view="workspace"]').click();
  await page.locator('[data-workflow-action="draft"]').click();
  await page.locator('.document-workspace-list-item').first().click();
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Document opened.'));
  await page.locator('[data-document-stage="filing"]').click();
  await page.locator('#authority-impact-base').selectOption(input.first);
  await page.locator('#authority-impact-target').selectOption(input.second);
  check('real_production_navigation_and_verified_fixture_generations');
  const compared=page.waitForResponse(r=>r.url().endsWith('/authority-change-impact/analyze'));
  await page.locator('#authority-impact-analyze').click();
  const response=await compared;
  assert.equal(response.status(),200);
  const result=await response.json();
  assert.equal(result.review_required,true);assert.equal(result.filing_ready,false);
  assert.deepEqual(result.impacted_source_ids,['maine-title-19a']);
  const details=page.locator('[data-authority-generation-drilldown]');
  await details.locator('summary').focus();await page.keyboard.press('Enter');
  for(const value of [input.first,input.second,input.revision_id,...input.hashes])assert.ok((await details.innerText()).includes(value));
  assert.ok(await details.evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await details.scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace('.json','.comparison.png')});
  check('meaningful_comparison_exact_hashes_revision_keyboard_drilldown');
  await page.locator('#authority-impact-approved').check();
  await page.locator('#authority-impact-base').selectOption(input.second);
  assert.equal(await page.locator('#authority-impact-approved').isChecked(),false);
  assert.equal(await page.locator('#authority-impact-build').isDisabled(),true);
  await page.locator('#authority-impact-base').selectOption(input.first);
  check('generation_change_clears_packet_approval');
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  const denied=page.waitForResponse(r=>r.url().includes('/authority-change-impact/status'));
  await page.locator('#authority-impact-refresh').click();
  assert.equal((await denied).status(),409);
  await page.waitForFunction(()=>document.getElementById('authority-impact-results').textContent.includes('Reload this matter'));
  assert.equal(await details.count(),0);
  check('wrong_matter_refused_old_results_removed');
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  await page.locator('#authority-impact-refresh').click();
  await page.waitForFunction(()=>document.getElementById('authority-impact-results').textContent.includes('2 verified generations available'));
  check('scope_error_recovers_after_explicit_reload');
  await page.locator('#authority-impact-approved').check();
  const built=page.waitForResponse(r=>r.url().endsWith('/authority-change-impact/build'));
  await page.locator('#authority-impact-build').click();
  const builtResponse=await built;
  assert.equal(builtResponse.status(),200);
  const packet=await builtResponse.json();
  assert.equal(packet.packet.revision_id,input.revision_id);
  assert.equal(packet.review_required,true);
  assert.equal(packet.artifacts.length,3);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Unencrypted review copies created'));
  check('explicit_exact_revision_packet_copies_created_review_required');
  await page.evaluate(()=>fetch('/__qa/corrupt-packet',{method:'POST'}));
  await page.locator('#authority-impact-refresh').click();
  await page.waitForFunction(()=>document.getElementById('authority-impact-results').textContent.includes('authority impact build unverified'));
  assert.equal(await page.locator('#authority-impact-artifacts a').count(),0);
  assert.match(await page.locator('#authority-impact-status-badge').innerText(),/blocker/);
  check('corrupt_saved_packet_visibly_blocks_no_download_links');
  assert.deepEqual(report.page_errors,[]);assert.deepEqual(report.external_requests,[]);
  assert.ok(!report.deadline_exceeded);report.passed=true;
}catch(error){report.failure=String(error.stack||error);if(page&&!page.isClosed())await page.screenshot({path:input.output.replace('.json','.failure.png')}).catch(()=>{});process.exitCode=1;}
finally{clearTimeout(watchdog);if(browser)await browser.close();report.browser_closed=true;report.elapsed_ms=Math.round(performance.now()-started);fs.writeFileSync(input.output,JSON.stringify(report,null,2)+'\n');}
