// Full shipped page with deterministic specialist response; real document API/storage.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(process.env.MFL_PROOF_NODE_MODULES,'playwright'));
const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
assert.equal(new URL(input.base_url).hostname,'127.0.0.1');
assert.ok(!fs.existsSync(input.output));
const report={model_inference:false,frozen_app:false,installed_package:false,ga_ready:false,
  page_errors:[],external_requests:[],checks:[]};
let browser, page;
const started=performance.now();
function checkpoint(name){
  report.checks.push(name);
  report.elapsed_ms=Math.round(performance.now()-started);
  fs.writeFileSync(input.output.replace(/\.json$/,'.progress.json'),JSON.stringify(report,null,2)+'\n');
}
// Close our own ephemeral browser before the parent's hard deadline. Preserve
// completed steps on disk even if an operation or final cleanup stops responding.
const watchdog=setTimeout(()=>{
  report.deadline_exceeded=true;
  fs.writeFileSync(input.output.replace(/\.json$/,'.progress.json'),JSON.stringify(report,null,2)+'\n');
  if(browser)void browser.close().catch(()=>{});
},90000);
try {
  browser=await chromium.launch({channel:'msedge',headless:true,
    env:{...process.env,APPDATA:process.env.TEMP,LOCALAPPDATA:process.env.TEMP},
    args:['--disable-background-networking','--disable-component-update']});
  report.browser_version=browser.version();
  const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
  await context.route('**/*',route=>{
    if(new URL(route.request().url()).origin!==input.base_url){report.external_requests.push(route.request().url());return route.abort();}
    return route.continue();
  });
  await context.addInitScript(()=>{
    localStorage.setItem('mfl-onboarding-complete','true');
    sessionStorage.setItem('mfl_local_capability_session_v1','a'.repeat(48));
  });
  page=await context.newPage();
  page.on('pageerror',error=>report.page_errors.push(error.message));
  await page.goto(input.base_url,{waitUntil:'networkidle'});
  assert.equal(await page.locator('body').getAttribute('data-production-ui'),'workbench');
  assert.deepEqual(report.page_errors,[]);
  checkpoint('shipped_page_boot');
  await page.locator('#question').fill('Prepare fictional source-bound working material.');
  await page.locator('#question').press('Enter');
  const answer=page.locator('.message.assistant').last();
  await page.waitForFunction(()=>document.querySelector('.message.assistant:last-child')?.textContent.includes('source-bound working material'));
  assert.match(await answer.innerText(),/Review required/);
  assert.ok((await answer.innerText()).includes(input.source_text));
  await answer.locator('[data-message-save-draft]').click();
  await page.locator('#document-workspace').waitFor({state:'visible'});
  await page.waitForFunction(()=>document.getElementById('document-workspace-editor').value.includes('source-bound working material'));
  assert.match(await page.locator('#document-workspace-status').innerText(),/not verified facts/);
  const privacy=page.locator('#document-workspace-storage-notice');
  assert.match(await privacy.innerText(),/encrypted with your local key/);
  assert.match(await privacy.innerText(),/not encrypted by this layer/);
  assert.equal(await privacy.getAttribute('role'),'status');
  report.storage_notice=await privacy.innerText();
  checkpoint('storage_scope_and_recovery_notice_visible');
  checkpoint('model_limitations_visible_on_handoff');
  // Simulate another window changing the host matter while this editor stays open.
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  const failed=page.waitForResponse(r=>r.url().endsWith('/api/document-workspace/documents')&&r.request().method()==='POST');
  await page.locator('#document-workspace-save-new').click();
  assert.equal((await failed).status(),409);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Nothing was saved'));
  assert.ok((await page.locator('#document-workspace-editor').inputValue()).includes(input.source_text));
  checkpoint('host_matter_change_rejected_editor_preserved');
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  const saved=page.waitForResponse(r=>r.url().endsWith('/api/document-workspace/documents')&&r.request().method()==='POST');
  await page.locator('#document-workspace-save-new').click();
  assert.equal((await saved).status(),200);
  await page.waitForFunction(()=>document.getElementById('document-workspace-history').textContent.includes('Facts, legal claims, relevance and current law are not verified'));
  checkpoint('saved_and_reopened_limitations_retained');
  await page.locator('[data-document-stage="filing"]').click();
  await page.locator('#document-review-facts').fill('Fictional notice supplied for review.');
  const preparing=page.waitForResponse(r=>r.url().endsWith('/review/prepare'));
  await page.locator('#document-review-prepare').click();
  const preparedResponse=await preparing;
  assert.equal(preparedResponse.status(),200);
  const preparedReview=await preparedResponse.json();
  assert.equal(preparedReview.storage_authenticated,true);
  await page.waitForFunction(()=>!document.getElementById('document-review-commit').disabled);
  const source=page.locator('#document-review-packet details').last();
  await source.locator('summary').focus(); await page.keyboard.press('Enter');
  assert.match(await source.innerText(),/Fictional notice supplied for review/);
  assert.ok((await source.innerText()).includes('offsets 0–'+'Fictional notice supplied for review.'.length));
  assert.match(await source.innerText(),/not official authority or a factual finding/);
  await page.locator('#document-reviewer-name').fill('Fictional reviewer');
  await page.locator('#document-reviewer-role').selectOption('other_reviewer');
  await page.locator('#document-review-decision').selectOption('request_changes');
  await page.locator('#document-review-notes').fill('Fictional private reviewer note.');
  page.once('dialog', dialog=>dialog.accept());
  const committing=page.waitForResponse(r=>r.url().endsWith('/review/commit'));
  await page.locator('#document-review-commit').click();
  const committedResponse=await committing;
  assert.equal(committedResponse.status(),200);
  assert.equal((await committedResponse.json()).filing_gate.filing_ready,false);
  await page.waitForFunction(()=>document.getElementById('document-review-history').textContent.includes('Fictional private reviewer note.'));
  assert.match(await page.locator('#document-review-history').innerText(),/New review packets and decisions are encrypted/);
  assert.match(await page.locator('#document-review-ledger-status').innerText(),/changes requested/);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Review recorded.'));
  assert.equal(await page.locator('#document-review-commit').isDisabled(),true);
  report.review_readability = await page.locator('#document-review-notes').evaluate(element => ({font:parseFloat(getComputedStyle(element).fontSize),width:element.getBoundingClientRect().width}));
  assert.ok(report.review_readability.font>=14);
  await page.locator('#document-review-history').scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace(/\.json$/,'.review.png')});
  await page.locator('.document-workspace-list-item').first().click();
  await page.waitForFunction(()=>document.getElementById('document-review-history').textContent.includes('Fictional private reviewer note.'));
  checkpoint('review_prepare_source_drilldown_encrypted_decision_reopened_blockers_retained');
  report.review_packet_id=preparedReview.request_id;
  await page.evaluate(()=>fetch('/__qa/review-interrupt',{method:'POST'}));
  const retryPreparation=page.waitForResponse(r=>r.url().endsWith('/review/prepare'));
  await page.locator('#document-review-prepare').click();
  assert.equal((await retryPreparation).status(),200);
  await page.waitForFunction(()=>!document.getElementById('document-review-commit').disabled);
  await page.locator('#document-review-notes').fill('Fictional interrupted review note.');
  page.once('dialog', dialog=>dialog.accept());
  const interruptedCommit=page.waitForResponse(r=>r.url().endsWith('/review/commit'));
  await page.locator('#document-review-commit').click();
  assert.equal((await interruptedCommit).status(),409);
  await page.waitForFunction(()=>document.querySelector('[data-review-head-status]')?.textContent.includes('Recovered an interrupted'));
  assert.match(await page.locator('#document-review-history').innerText(),/Fictional interrupted review note/);
  assert.equal(await page.locator('#document-review-commit').isDisabled(),true);
  await page.locator('[data-review-head-status]').scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace(/\.json$/,'.recovered.png')});
  checkpoint('interrupted_confirmed_review_recovered_and_disclosed');
  await page.evaluate(()=>fetch('/__qa/review-truncate',{method:'POST'}));
  await page.locator('.document-workspace-list-item').first().click();
  await page.waitForFunction(()=>document.querySelector('[data-review-head-status]')?.textContent.includes('Review history is incomplete'));
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Document opened for inspection.'));
  assert.equal(await page.locator('#document-review-prepare').isDisabled(),true);
  assert.equal(await page.locator('#document-review-commit').isDisabled(),true);
  assert.match(await page.locator('#document-review-ledger-status').innerText(),/not authenticated/);
  await page.locator('[data-review-head-status]').scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace(/\.json$/,'.truncated.png')});
  checkpoint('truncated_review_blocks_prior_approval_and_new_review_actions');
  await page.locator('[data-document-stage="compose"]').click();
  report.history=await page.locator('#document-workspace-history').innerText();
  assert.match(report.history,/model’s other prose was withheld/);
  assert.match(await page.locator('#document-workspace-meta').innerText(),/review required/i);
  await privacy.scrollIntoViewIfNeeded();
  const layout=await privacy.evaluate(element=>{
    const rect=element.getBoundingClientRect(), next=element.nextElementSibling.getBoundingClientRect();
    return {scrollHeight:element.scrollHeight,clientHeight:element.clientHeight,
      bottom:rect.bottom,nextTop:next.top,font:parseFloat(getComputedStyle(element).fontSize)};
  });
  assert.ok(layout.scrollHeight<=layout.clientHeight+1,'Privacy notice must not clip');
  assert.ok(layout.bottom<=layout.nextTop+1,'Privacy notice must not overlap the editor');
  assert.ok(layout.font>=14);
  report.storage_notice_layout=layout;
  checkpoint('storage_notice_not_clipped_or_overlapping');
  await page.screenshot({path:input.output.replace(/\.json$/,'.png')});
  // Existing legacy workspace remains readable, but cannot receive plaintext writes.
  await page.locator('#document-review-attested').check();
  await page.locator('#document-workspace-new').click();
  for(const id of ['document-review-facts','document-review-notes','document-reviewer-name'])assert.equal(await page.locator('#'+id).inputValue(),'');
  assert.equal(await page.locator('#document-review-attested').isChecked(),false);
  // Independently exercise the matter boundary even when no active document exists.
  await page.locator('#document-review-notes').fill('Fictional old-matter unsaved note');
  await page.evaluate(()=>fetch('/__qa/legacy',{method:'POST'}));
  await page.locator('#document-workspace-refresh').click();
  await page.waitForFunction(()=>document.getElementById('document-workspace-storage-notice').textContent.includes('Legacy draft storage'));
  assert.equal(await page.locator('#document-workspace-save-new').isDisabled(),true);
  await page.locator('.document-workspace-list-item').first().click();
  await page.waitForFunction(()=>document.getElementById('document-workspace-editor').value.includes('Fictional legacy draft, preserved'));
  assert.equal(await page.locator('#document-workspace-editor').evaluate(e=>e.readOnly),true);
  assert.equal(await page.locator('#document-workspace-propose').isDisabled(),true);
  assert.equal(await page.locator('#document-workspace-delete').isDisabled(),true);
  assert.equal(await page.locator('#document-review-prepare').isDisabled(),true);
  assert.equal(await page.locator('#document-review-commit').isDisabled(),true);
  assert.equal(await page.locator('#document-review-notes').inputValue(),'');
  assert.equal(await page.locator('#document-review-decision').inputValue(),'request_changes');
  checkpoint('new_document_and_matter_switch_clear_review_inputs_and_attestation');
  checkpoint('legacy_draft_readable_with_mutations_disabled');
  const migration=page.locator('#document-migration-review');
  await page.locator('#document-migration-review-open').click();
  await page.waitForFunction(()=>document.getElementById('document-migration-review').textContent.includes('1 documents · 1 revisions'));
  assert.match(await migration.innerText(),/No migration performed/);
  assert.match(await migration.innerText(),/encrypted byte-exact originals/);
  const drilldown=migration.locator('summary');
  await drilldown.focus(); await page.keyboard.press('Enter');
  assert.equal(await migration.locator('details').evaluate(e=>e.open),true);
  assert.match(await migration.innerText(),/SHA-256 [a-f0-9]{64}/);
  await migration.getByRole('button',{name:'Open current draft'}).click();
  assert.equal(await page.locator('#document-workspace-editor').evaluate(e=>e.readOnly),true);
  checkpoint('legacy_inventory_review_hash_drilldown_and_original_draft');
  await migration.scrollIntoViewIfNeeded();
  report.migration_layout = await migration.locator('details p').first().evaluate(item=>{
    const text=item.querySelector('span').getBoundingClientRect();
    const button=item.querySelector('button').getBoundingClientRect();
    return {textBottom:text.bottom,buttonTop:button.top,textRight:text.right,panelRight:item.getBoundingClientRect().right};
  });
  assert.ok(report.migration_layout.textBottom<=report.migration_layout.buttonTop);
  assert.ok(report.migration_layout.textRight<=report.migration_layout.panelRight+1);
  await page.screenshot({path:input.output.replace(/\.json$/,'.migration.png')});
  await privacy.scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace(/\.json$/,'.legacy.png')});
  let migrationRequests=0;
  page.on('request', request=>{if(request.url().endsWith('/api/document-workspace/migration-execute')) migrationRequests++;});
  page.once('dialog', dialog=>dialog.dismiss());
  await page.locator('#document-migration-execute').click();
  assert.equal(migrationRequests,0,'Declining must not start migration');
  const completed=page.waitForResponse(response=>response.url().endsWith('/api/document-workspace/migration-execute'));
  page.once('dialog', dialog=>dialog.accept());
  await page.locator('#document-migration-execute').click();
  const migrated=await completed;
  assert.equal(migrated.status(),200);
  const receipt=await migrated.json();
  assert.equal(receipt.migration_performed,true);
  assert.equal(receipt.original_bytes_recoverable,true);
  assert.equal(receipt.all_workspace_files_encrypted,false);
  await page.waitForFunction(()=>!document.getElementById('document-workspace-editor').readOnly);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Draft JSON migration verified:'));
  assert.match(await privacy.innerText(),/New draft text/);
  assert.equal(await page.locator('#document-migration-execute').count(),0);
  assert.match(await page.locator('#document-workspace-editor').inputValue(),/Fictional legacy draft, preserved/);
  report.migration_receipt=receipt;
  checkpoint('declined_migration_no_request_then_confirmed_conversion_and_reopen');
  const migrationStatus=page.locator('#document-workspace-status');
  await migrationStatus.scrollIntoViewIfNeeded();
  report.migration_status_layout=await migrationStatus.evaluate(element=>({font:parseFloat(getComputedStyle(element).fontSize),height:element.clientHeight,scrollHeight:element.scrollHeight}));
  assert.ok(report.migration_status_layout.font>=14);
  assert.ok(report.migration_status_layout.scrollHeight<=report.migration_status_layout.height+1);
  await page.screenshot({path:input.output.replace(/\.json$/,'.migrated.png')});
  assert.deepEqual(report.page_errors,[]);
  assert.deepEqual(report.external_requests,[]);
  assert.ok(!report.deadline_exceeded,'The whole journey must finish within its budget');
  report.passed=true;
} catch(error) {
  report.failure=String(error.stack||error);
  if(page&&!page.isClosed())await page.screenshot({path:input.output.replace(/\.json$/,'.failure.png')}).catch(()=>{});
  process.exitCode=1;
} finally {
  clearTimeout(watchdog);
  if(browser)await browser.close();
  report.browser_closed=true;
  report.elapsed_ms=Math.round(performance.now()-started);
  fs.writeFileSync(input.output,JSON.stringify(report,null,2)+'\n');
}
