import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(process.env.MFL_PROOF_NODE_MODULES,'playwright'));
const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
assert.equal(new URL(input.base_url).hostname,'127.0.0.1');
assert.ok(!fs.existsSync(input.output));
const report={fictional_only:true,model_inference:false,frozen_app:false,page_errors:[],external_requests:[],checks:[]};
let browser,page;
const started=performance.now();
function check(name){report.checks.push(name);fs.writeFileSync(input.output.replace('.json','.progress.json'),JSON.stringify(report,null,2));}
const watchdog=setTimeout(()=>{report.deadline_exceeded=true;if(browser)void browser.close().catch(()=>{});},90000);
try{
  browser=await chromium.launch({channel:'msedge',headless:true,env:{...process.env,APPDATA:process.env.TEMP,LOCALAPPDATA:process.env.TEMP},args:['--disable-background-networking','--disable-component-update']});
  report.browser_version=browser.version();
  const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
  await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==input.base_url){report.external_requests.push(route.request().url());return route.abort();}return route.continue();});
  await context.addInitScript(()=>{localStorage.setItem('mfl-onboarding-complete','true');sessionStorage.setItem('mfl_local_capability_session_v1','a'.repeat(48));});
  page=await context.newPage();page.on('pageerror',error=>report.page_errors.push(error.message));
  await page.goto(input.base_url,{waitUntil:'networkidle'});
  assert.equal(await page.locator('body').getAttribute('data-production-ui'),'workbench');
  await page.locator('#v8-view-menu summary').click();
  await page.locator('[data-v8-view="workspace"]').click();
  await page.locator('[data-workflow-action="draft"]').click();
  await page.locator('.document-workspace-list-item').first().click();
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Document opened.'));
  check('production_navigation_and_current_document');
  await page.locator('[data-document-stage="filing"]').click();
  const label='Fictional reviewer <not-html>';
  await page.locator('#filing-packet-reviewer-label').fill(label);
  await page.locator('#filing-packet-reviewer-role').selectOption('other_reviewer');
  await page.locator('#filing-packet-exclusive').check();
  const assigned=page.waitForResponse(r=>r.url().endsWith('/assignments')&&r.request().method()==='POST');
  await page.locator('#filing-packet-assign').click();
  assert.equal((await assigned).status(),200);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Encrypted reviewer assignment recorded'));
  const details=page.locator('[data-assignment-history]');
  await details.locator('summary').focus();await page.keyboard.press('Enter');
  assert.ok((await details.innerText()).includes(label));
  assert.ok((await details.innerText()).includes(input.revision_id));
  assert.match(await details.innerText(),/Event SHA-256 [a-f0-9]{64}/);
  assert.equal(await details.locator('not-html').count(),0);
  assert.match(await page.locator('[data-assignment-privacy]').innerText(),/encrypted/);
  await details.scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace('.json','.encrypted.png')});
  check('assignment_saved_exact_revision_hash_drilldown_review_required');
  await page.locator('#document-workspace-close').click();
  const reopened=page.waitForResponse(r=>r.url().includes('/api/reviewed-filing-packet/status'));
  await page.locator('[data-workflow-action="draft"]').click();
  assert.equal((await reopened).status(),200);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Document opened.'));
  await page.waitForFunction(()=>document.getElementById('filing-packet-results').textContent.includes('Fictional reviewer <not-html>'));
  check('reopened_authenticated_assignment');
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  const denied=page.waitForResponse(r=>r.url().endsWith('/assignments')&&r.request().method()==='POST');
  await page.locator('#filing-packet-assign').click();
  const denial=await denied;
  assert.equal(denial.status(),409);
  assert.equal((await denial.json()).detail,'review_active_matter_mismatch');
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Reload assignments before retrying'));
  check('wrong_matter_assignment_refused');
  await page.evaluate(()=>fetch('/__qa/switch',{method:'POST'}));
  await page.evaluate(()=>fetch('/__qa/legacy',{method:'POST'}));
  await page.locator('#filing-packet-refresh').click();
  await page.waitForFunction(()=>document.querySelector('[data-assignment-privacy]')?.textContent.includes('Legacy assignment history is read-only'));
  assert.equal(await page.locator('#filing-packet-assign').isDisabled(),true);
  assert.match(await page.locator('[data-assignment-privacy]').innerText(),/inspection only/);
  await details.locator('summary').click();
  assert.ok((await details.innerText()).includes(label));
  await details.scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace('.json','.legacy.png')});
  check('legacy_history_inspection_only_mutation_disabled');
  assert.equal(await page.locator('#assignment-migration-run').isDisabled(),true);
  assert.match(await page.locator('#assignment-migration-preview').innerText(),/Original SHA-256: [a-f0-9]{64}/);
  await page.setViewportSize({width:1280,height:900});
  await page.locator('#assignment-migration-panel').scrollIntoViewIfNeeded();
  assert.ok(await page.locator('#assignment-migration-panel').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  assert.ok(await page.locator('#assignment-migration-confirm').evaluate(el=>parseFloat(getComputedStyle(el.parentElement).fontSize)>=14));
  await page.screenshot({path:input.output.replace('.json','.preview.png')});
  await page.locator('#assignment-migration-confirm').focus();await page.keyboard.press('Space');
  assert.equal(await page.locator('#assignment-migration-run').isDisabled(),false);
  await page.evaluate(()=>fetch('/__qa/change-legacy',{method:'POST'}));
  const stale=page.waitForResponse(r=>r.url().endsWith('/assignments/migrate'));
  await page.locator('#assignment-migration-run').click();
  assert.equal((await stale).status(),409);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Reload assignment history to confirm its state'));
  assert.equal(await page.locator('#assignment-migration-run').isDisabled(),true);
  await page.locator('#filing-packet-refresh').click();
  await page.locator('#assignment-migration-panel').waitFor({state:'visible'});
  assert.equal(await page.locator('#assignment-migration-confirm').isChecked(),false);
  check('stale_preview_rejected_recovery_requires_fresh_confirmation');
  await page.locator('#assignment-migration-confirm').check();
  const migrated=page.waitForResponse(r=>r.url().endsWith('/assignments/migrate'));
  await page.locator('#assignment-migration-run').click();
  const migrationResponse=await migrated;
  assert.equal(migrationResponse.status(),200);
  const migrationPayload=await migrationResponse.json();
  assert.deepEqual(migrationPayload.active,[]);
  assert.equal(migrationPayload.migration.historical_assignments_activated,false);
  assert.equal(migrationPayload.migration.receipt.event_count,1);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Historical assignments remain inactive'));
  const receipt=page.locator('[data-assignment-migration-receipt]');
  await receipt.locator('summary').focus();await page.keyboard.press('Enter');
  assert.ok(await receipt.locator('summary').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=14));
  assert.ok((await receipt.innerText()).includes(migrationPayload.migration.receipt.original_sha256));
  assert.equal(await page.locator('#assignment-migration-panel').isHidden(),true);
  await receipt.scrollIntoViewIfNeeded();
  await page.screenshot({path:input.output.replace('.json','.migrated.png')});
  check('confirmed_migration_exact_original_receipt_no_historical_activation');
  await page.locator('#filing-packet-reviewer-label').fill('Fictional current reviewer');
  const fresh=page.waitForResponse(r=>r.url().endsWith('/assignments')&&r.request().method()==='POST');
  await page.locator('#filing-packet-assign').click();
  assert.equal((await fresh).status(),200);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Encrypted reviewer assignment recorded'));
  await page.locator('#document-workspace-close').click();
  const reload=page.waitForResponse(r=>r.url().includes('/api/reviewed-filing-packet/status'));
  await page.locator('[data-workflow-action="draft"]').click();
  const reopenedPayload=await (await reload).json();
  assert.equal(reopenedPayload.assignments.active.length,1);
  assert.equal(reopenedPayload.assignments.active[0].reviewer_label,'Fictional current reviewer');
  assert.equal(reopenedPayload.assignments.migration.receipt.original_sha256,migrationPayload.migration.receipt.original_sha256);
  await page.waitForFunction(()=>document.getElementById('document-workspace-status').textContent.includes('Document opened.'));
  check('new_assignment_reopens_with_migration_original_preserved');
  assert.deepEqual(report.page_errors,[]);assert.deepEqual(report.external_requests,[]);
  assert.ok(!report.deadline_exceeded);
  report.passed=true;
}catch(error){report.failure=String(error.stack||error);if(page&&!page.isClosed())await page.screenshot({path:input.output.replace('.json','.failure.png')}).catch(()=>{});process.exitCode=1;}
finally{clearTimeout(watchdog);if(browser)await browser.close();report.browser_closed=true;report.elapsed_ms=Math.round(performance.now()-started);fs.writeFileSync(input.output,JSON.stringify(report,null,2)+'\n');}
