from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class EndpointSpec:
    method: str
    path: str
    purpose: str
    review_required: bool = True

    def as_dict(self) -> dict[str, Any]:
        return {
            "method": self.method,
            "path": self.path,
            "purpose": self.purpose,
            "review_required": self.review_required,
        }


REQUIRED_API_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec("POST", "/api/intake/matter", "register a confidential legal matter"),
    EndpointSpec("POST", "/api/intake/document", "ingest a matter document"),
    EndpointSpec("POST", "/api/query", "ask a source-grounded Maine family-law question"),
    EndpointSpec("POST", "/api/research", "retrieve relevant Maine authority"),
    EndpointSpec("POST", "/api/draft", "generate a review-required draft"),
    EndpointSpec("POST", "/api/review", "review a draft or uploaded text"),
    EndpointSpec("POST", "/api/citations/verify", "resolve and verify citations"),
    EndpointSpec("POST", "/api/quotes/verify", "verify quoted source spans"),
    EndpointSpec("POST", "/api/evidence/map", "map facts to evidence"),
    EndpointSpec("POST", "/api/timeline/build", "build a case timeline"),
    EndpointSpec("POST", "/api/filing-ready/check", "evaluate filing-readiness blockers"),
    EndpointSpec("GET", "/api/deliberation/presets", "list local deliberation presets"),
    EndpointSpec("GET", "/api/deliberation/tools", "list local deliberation tools"),
    EndpointSpec("POST", "/api/deliberation/runs", "create a local deliberation run"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}", "fetch a local deliberation run"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/confirm", "freeze and confirm a local-only scope"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/start", "start a local deliberation run"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/cancel", "cancel a local deliberation run"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}/events", "list local deliberation events"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}/claims", "list local deliberation claims"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}/positions", "list worker positions"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}/synthesis", "fetch the local deliberation synthesis"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/outbound-preview", "preview an exact outbound provider manifest"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/approve-outbound", "approve an outbound provider manifest"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/start-external", "start an approved external provider run"),
    EndpointSpec("GET", "/api/deliberation/runs/{run_id}/usage", "fetch provider usage for a deliberation run"),
    EndpointSpec("POST", "/api/deliberation/runs/{run_id}/tools/{tool_name}", "invoke a read-only deliberation tool"),
    EndpointSpec("GET", "/api/providers", "list supported provider connections"),
    EndpointSpec("POST", "/api/providers/{provider_id}/connect", "connect a BYOK provider"),
    EndpointSpec("POST", "/api/providers/{provider_id}/disconnect", "disconnect a provider"),
    EndpointSpec("POST", "/api/providers/{provider_id}/health", "check provider readiness"),
    EndpointSpec("GET", "/api/providers/{provider_id}/capabilities", "fetch provider capability report"),
    EndpointSpec("GET", "/api/providers/{provider_id}/status", "fetch provider status and sharing summary"),
    EndpointSpec("GET", "/api/providers/sharing-summary", "fetch the current provider sharing summary"),
    EndpointSpec("POST", "/api/providers/disconnect-all", "disconnect all connected providers"),
    EndpointSpec("POST", "/api/providers/revoke-all", "revoke all provider credentials"),
    EndpointSpec("POST", "/api/providers/return-local-only", "return provider sessions to local-only mode"),
    EndpointSpec("GET", "/api/children", "list child continuity profiles"),
    EndpointSpec("POST", "/api/children", "create a child continuity profile"),
    EndpointSpec("GET", "/api/children/{child_id}", "fetch a child continuity profile"),
    EndpointSpec("PATCH", "/api/children/{child_id}", "update a child continuity profile"),
    EndpointSpec("GET", "/api/children/{child_id}/continuity", "fetch the child continuity summary"),
    EndpointSpec("POST", "/api/children/{child_id}/continuity/build", "build a child continuity snapshot"),
    EndpointSpec("POST", "/api/children/{child_id}/events", "add a child continuity event"),
    EndpointSpec("PATCH", "/api/children/{child_id}/events/{event_id}", "update a child continuity event"),
    EndpointSpec("GET", "/api/children/{child_id}/school", "fetch child school continuity items"),
    EndpointSpec("GET", "/api/children/{child_id}/care", "fetch child care continuity items"),
    EndpointSpec("GET", "/api/children/{child_id}/services", "fetch child services continuity items"),
    EndpointSpec("GET", "/api/children/{child_id}/gaps", "fetch child continuity gaps"),
    EndpointSpec("POST", "/api/children/{child_id}/schedule-scenarios", "build neutral schedule scenarios"),
    EndpointSpec("POST", "/api/children/{child_id}/claims/review", "review child continuity claims and contradictions"),
    EndpointSpec("POST", "/api/children/{child_id}/packet", "export a child-focused continuity packet"),
    EndpointSpec("GET", "/api/communications", "fetch the communications and parenting-time workbench"),
    EndpointSpec("POST", "/api/communications/import", "import local communications records"),
    EndpointSpec("GET", "/api/communications/messages", "list imported communications messages"),
    EndpointSpec("GET", "/api/communications/threads", "list reconstructed communications threads"),
    EndpointSpec("GET", "/api/communications/schedule", "fetch schedule change history"),
    EndpointSpec("GET", "/api/communications/parenting-time", "fetch parenting-time event review"),
    EndpointSpec("GET", "/api/communications/agreements", "fetch agreement and dispute mappings"),
    EndpointSpec("GET", "/api/communications/claims", "fetch communication claims"),
    EndpointSpec("GET", "/api/communications/completeness", "fetch communication completeness"),
    EndpointSpec("GET", "/api/communications/review-history", "fetch communications review history"),
    EndpointSpec("POST", "/api/communications/exports", "export a communications review bundle"),
    EndpointSpec("GET", "/api/hearing-media", "fetch the hearing multimedia workbench"),
    EndpointSpec("GET", "/api/hearing-media/media", "list imported hearing media"),
    EndpointSpec("POST", "/api/hearing-media/import", "import local hearing media records"),
    EndpointSpec("GET", "/api/hearing-media/media/{media_id}", "fetch a hearing media record"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/transcribe", "create a hearing transcript"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/speaker-review", "review speaker labels in a transcript"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/timeline/build", "build a hearing timeline"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/compare", "compare an official transcript to the derived transcript"),
    EndpointSpec("GET", "/api/hearing-media/media/{media_id}/exhibits", "build exhibit references from the transcript"),
    EndpointSpec("GET", "/api/hearing-media/media/{media_id}/appellate-record", "fetch the appellate record completeness checklist"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/citations", "record transcript citations"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/privacy-scan", "run a local privacy scan on the transcript"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/redacted-copy", "create a separate redacted transcript derivative"),
    EndpointSpec("POST", "/api/hearing-media/media/{media_id}/cancel", "cancel a hearing transcription workflow"),
    EndpointSpec("GET", "/api/hearing-media/review-history", "fetch hearing media review history"),
    EndpointSpec("POST", "/api/hearing-media/exports", "export a hearing media review bundle"),
    EndpointSpec("GET", "/api/productivity", "fetch the matter Productivity Studio"),
    EndpointSpec("POST", "/api/productivity/inbox/configurations", "configure a safe matter inbox"),
    EndpointSpec("POST", "/api/productivity/inbox/{inbox_id}/scan", "review an explicit inbox candidate manifest"),
    EndpointSpec("POST", "/api/productivity/recipes", "save an allow-listed local workflow recipe"),
    EndpointSpec("POST", "/api/productivity/recipes/{recipe_id}/run", "run a confirmed local workflow recipe"),
    EndpointSpec("POST", "/api/productivity/calendar/exports", "create a review-required ICS export"),
    EndpointSpec("POST", "/api/productivity/hardware/optimize", "create a hardware-safe local execution plan"),
    EndpointSpec("POST", "/api/productivity/pinboard/items", "pin an exact source span"),
    EndpointSpec("POST", "/api/productivity/redaction/projects", "create a source-bound redaction review project"),
    EndpointSpec("POST", "/api/productivity/redaction/projects/{project_id}/finalize", "create a reviewed redacted derivative"),
    EndpointSpec("POST", "/api/productivity/next-actions/refresh", "build a corrective matter action queue"),
    EndpointSpec("POST", "/api/productivity/courtroom/sessions", "create a source-bound presentation session"),
    EndpointSpec("POST", "/api/productivity/backups/schedules", "configure encrypted matter backups"),
    EndpointSpec("POST", "/api/productivity/backups/run", "run and verify an encrypted matter backup"),
    EndpointSpec("GET", "/api/productivity/backups/{backup_id}/verify", "verify an encrypted matter backup"),
    EndpointSpec("POST", "/api/productivity/backups/{backup_id}/restore", "restore into an isolated recovery directory"),
    EndpointSpec("GET", "/api/productivity/sources/{item_id}", "inspect an exact Productivity Studio source item"),
    EndpointSpec("GET", "/api/addons", "fetch the matter Add-on Studio"),
    EndpointSpec("POST", "/api/addons/{addon_id}/actions", "run one local review-required add-on action"),
    EndpointSpec("GET", "/api/addons/{addon_id}/results/{result_id}", "inspect an exact add-on result"),
    EndpointSpec("POST", "/api/addons/{addon_id}/results/{result_id}/review", "record an immutable add-on review decision"),
    EndpointSpec("GET", "/api/addons/integrity", "verify the add-on result and audit hash chain"),
    EndpointSpec("GET", "/api/addons/{addon_id}/results/{result_id}/artifacts/{artifact_id}", "open an exact decrypted add-on artifact"),
    EndpointSpec("POST", "/api/privacy/disconnect-all", "disconnect all connected providers"),
    EndpointSpec("POST", "/api/privacy/revoke-all", "revoke all provider credentials"),
    EndpointSpec("GET", "/api/security/privacy/dashboard", "fetch the security and privacy dashboard"),
    EndpointSpec("POST", "/api/security/privacy/backup", "create a hashed matter backup"),
    EndpointSpec("POST", "/api/security/privacy/restore", "verify and rehearse a matter restore"),
    EndpointSpec("POST", "/api/security/privacy/injection-scan", "run prompt-injection defense"),
    EndpointSpec("POST", "/api/security/privacy/diagnostics/redact", "redact diagnostic payloads"),
    EndpointSpec("POST", "/api/security/privacy/retention", "resolve a data-class retention policy"),
    EndpointSpec("GET", "/api/security/privacy/audit", "verify the security audit chain"),
    EndpointSpec("POST", "/api/security/privacy/incidents/open", "open a security incident"),
    EndpointSpec("POST", "/api/security/privacy/incidents/close", "close a security incident"),
    EndpointSpec("GET", "/api/release-control-center/status", "fetch the release control center status"),
    EndpointSpec("GET", "/api/matters/{matter_id}/command-center", "fetch the matter command center"),
    EndpointSpec("POST", "/api/matters/{matter_id}/review-snapshot", "freeze a whole-matter review snapshot"),
    EndpointSpec("POST", "/api/matters/{matter_id}/evidence-packet", "export a whole-matter evidence packet"),
    EndpointSpec("GET", "/api/matters/{matter_id}/evidence-packets", "list exported evidence packets"),
    EndpointSpec("GET", "/api/evidence-packets/{packet_id}", "fetch an exported evidence packet"),
    EndpointSpec("GET", "/api/evidence-packets/{packet_id}/receipt", "fetch an evidence packet receipt"),
    EndpointSpec("POST", "/api/evidence-packets/{packet_id}/review", "record a review of an evidence packet"),
    EndpointSpec("POST", "/api/evidence-packets/{packet_id}/compare", "compare two evidence packets"),
    EndpointSpec("GET", "/api/evals/status", "report evaluation and review lab status"),
    EndpointSpec("GET", "/api/evals/datasets", "list evaluation datasets"),
    EndpointSpec("GET", "/api/evals/datasets/{dataset_id}", "fetch an evaluation dataset"),
    EndpointSpec("POST", "/api/evals/queue/build", "build an evaluation annotation queue"),
    EndpointSpec("GET", "/api/evals/assignments", "list evaluation assignments"),
    EndpointSpec("POST", "/api/evals/assignments", "build an evaluation assignment bundle"),
    EndpointSpec("GET", "/api/evals/rows/{row_id}", "fetch a queue row or promoted row"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/review", "record a first review"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/recuse", "record a reviewer recusal"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/second-review", "record an independent second review"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/adjudicate", "resolve a review disagreement"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/promote", "promote an adjudicated row to gold"),
    EndpointSpec("POST", "/api/evals/rows/{row_id}/supersede", "promote a corrected superseding row"),
    EndpointSpec("POST", "/api/evals/run", "run a regression evaluation"),
    EndpointSpec("POST", "/api/evals/runs/{run_id}/cancel", "cancel a regression evaluation"),
    EndpointSpec("GET", "/api/evals/runs/{run_id}", "fetch a regression evaluation run"),
    EndpointSpec("GET", "/api/evals/metrics", "fetch latest metric evidence"),
    EndpointSpec("GET", "/api/evals/failures", "fetch failure clusters"),
    EndpointSpec("GET", "/api/evals/release-comparison", "compare the latest run with the accepted release"),
    EndpointSpec("POST", "/api/evals/exports/build", "build the external review export bundle"),
    EndpointSpec("GET", "/api/evals/exports/latest", "fetch the latest external review export bundle"),
    EndpointSpec("GET", "/api/authority/status", "report the active official authority library status"),
    EndpointSpec("GET", "/api/authority/builds", "list official authority builds"),
    EndpointSpec("GET", "/api/authority/sources", "browse the official authority library"),
    EndpointSpec("GET", "/api/authority/sources/{source_id}", "fetch an admitted official source"),
    EndpointSpec("GET", "/api/authority/sources/{source_id}/span", "inspect an exact official source span"),
    EndpointSpec("GET", "/api/authority/update-report/{build_id}", "fetch an official authority update report"),
    EndpointSpec("POST", "/api/authority/update", "update official Maine sources"),
    EndpointSpec("POST", "/api/authority/update/cancel", "cancel an in-progress official source update"),
    EndpointSpec("POST", "/api/authority/citations/resolve", "resolve citation variants against the active authority generation"),
    EndpointSpec("POST", "/api/authority/verify-output", "verify an answer against the active immutable authority generation"),
    EndpointSpec("GET", "/api/sources", "browse admitted sources and source cards"),
    EndpointSpec("GET", "/api/sources/{source_id}", "fetch an admitted source card or source text"),
    EndpointSpec("POST", "/api/intake/report", "register a matter intake report"),
    EndpointSpec("GET", "/api/matters/{matter_id}/evidence-packet", "fetch a review-required evidence packet"),
    EndpointSpec("GET", "/api/governance/controls", "fetch the governance control registry"),
    EndpointSpec("GET", "/api/governance/framework-mappings", "fetch framework mappings"),
    EndpointSpec("GET", "/api/governance/policies", "fetch institutional policies"),
    EndpointSpec("GET", "/api/governance/policy-packs", "fetch policy packs"),
    EndpointSpec("POST", "/api/governance/policy-packs/draft", "draft a policy pack"),
    EndpointSpec("POST", "/api/governance/policy-packs/compare", "compare two policy packs"),
    EndpointSpec("POST", "/api/governance/reviews", "review a policy pack"),
    EndpointSpec("POST", "/api/governance/activation", "activate a policy pack"),
    EndpointSpec("POST", "/api/governance/rollback", "rollback a policy pack"),
    EndpointSpec("POST", "/api/governance/expire", "expire a policy pack"),
    EndpointSpec("POST", "/api/governance/supersede", "supersede a policy pack"),
    EndpointSpec("GET", "/api/governance/model-cards", "fetch model cards"),
    EndpointSpec("GET", "/api/governance/data-cards", "fetch data cards"),
    EndpointSpec("GET", "/api/governance/vendor-risks", "fetch vendor risk records"),
    EndpointSpec("GET", "/api/governance/exceptions", "fetch governance exceptions"),
    EndpointSpec("POST", "/api/governance/exceptions", "record a governance exception"),
    EndpointSpec("GET", "/api/governance/sign-offs", "fetch sign-off matrix"),
    EndpointSpec("POST", "/api/governance/sign-offs", "record a sign-off"),
    EndpointSpec("GET", "/api/governance/diligence-packet", "build the redacted diligence packet"),
    EndpointSpec("GET", "/api/governance/history", "fetch governance change history"),
    EndpointSpec("GET", "/api/health", "service health", review_required=False),
    EndpointSpec("GET", "/api/release-pilot-hardening/status", "fetch release pilot hardening status"),
    EndpointSpec("POST", "/api/release-pilot-hardening/evidence/audit", "audit release evidence"),
    EndpointSpec("POST", "/api/release-pilot-hardening/observability/self-test", "run release observability self-test"),
    EndpointSpec("POST", "/api/release-pilot-hardening/backup-restore/drill", "run release backup and restore drill"),
    EndpointSpec("POST", "/api/release-pilot-hardening/pilot/participants", "register a pilot participant"),
    EndpointSpec("POST", "/api/release-pilot-hardening/pilot/sessions", "start a pilot session"),
    EndpointSpec("POST", "/api/release-pilot-hardening/pilot/feedback", "record pilot feedback"),
    EndpointSpec("GET", "/api/release-pilot-hardening/pilot/dashboard", "fetch the pilot dashboard"),
    EndpointSpec("GET", "/api/attorney-sandbox-operations/status", "fetch attorney sandbox operations status"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/programs", "create an attorney sandbox program"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/cohorts", "create an attorney sandbox cohort"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/assignments", "create an attorney sandbox assignment"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/reviews", "submit an attorney sandbox review"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/sessions/complete", "complete an attorney sandbox session"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/feedback/triage", "triage attorney sandbox feedback"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/attestations", "record an attorney sandbox attestation"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/eval/export", "export attorney sandbox eval candidates"),
    EndpointSpec("POST", "/api/attorney-sandbox-operations/evidence/build", "build attorney sandbox evidence"),
    EndpointSpec("GET", "/api/attorney-sandbox-operations/artifacts/{token}", "download an attorney sandbox artifact"),
    EndpointSpec("GET", "/api/limited-real-matter-pilot/status", "fetch limited real-matter pilot status"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/programs", "create a limited real-matter pilot program"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/matters", "enroll a limited real-matter matter"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/work-products", "record a real-matter work product"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/daily-reviews", "record a real-matter daily review"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/exports", "record a real-matter export attempt"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/incidents", "record a real-matter incident"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/incidents/update", "update a real-matter incident"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/signoffs", "record a real-matter signoff"),
    EndpointSpec("POST", "/api/limited-real-matter-pilot/evidence/build", "build limited real-matter evidence"),
    EndpointSpec("GET", "/api/limited-real-matter-pilot/artifacts/{token}", "download a real-matter artifact"),
    EndpointSpec("GET", "/api/ga-release-candidate/status", "fetch GA release candidate status"),
    EndpointSpec("POST", "/api/ga-release-candidate/candidates", "create a GA release candidate"),
    EndpointSpec("POST", "/api/ga-release-candidate/artifacts", "record a GA release candidate artifact"),
    EndpointSpec("POST", "/api/ga-release-candidate/signoffs", "record a GA release candidate signoff"),
    EndpointSpec("POST", "/api/ga-release-candidate/blockers", "record a GA release candidate blocker"),
    EndpointSpec("POST", "/api/ga-release-candidate/freeze", "freeze a GA release candidate"),
    EndpointSpec("POST", "/api/ga-release-candidate/evidence/build", "build GA release candidate evidence"),
    EndpointSpec("GET", "/api/ga-release-candidate/artifacts/{token}", "download a GA release candidate artifact"),
    EndpointSpec("GET", "/api/ga-shipment-readiness/status", "fetch GA shipment readiness status"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/shipments", "create a GA shipment readiness record"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/artifacts", "record a GA shipment artifact"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/controls", "record a GA shipment control"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/channels", "record a GA shipment channel"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/blockers", "record a GA shipment blocker"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/evaluate", "evaluate GA shipment readiness"),
    EndpointSpec("POST", "/api/ga-shipment-readiness/evidence/build", "build GA shipment readiness evidence"),
    EndpointSpec("GET", "/api/ga-shipment-readiness/artifacts/{token}", "download a GA shipment readiness artifact"),
    EndpointSpec("GET", "/api/models", "list admitted and candidate models"),
    EndpointSpec("GET", "/api/models/{model_id}", "fetch a model registry record"),
    EndpointSpec("POST", "/api/models/import", "import a model registry record"),
    EndpointSpec("POST", "/api/models/{model_id}/validate", "validate a model registry record"),
    EndpointSpec("POST", "/api/models/{model_id}/benchmark", "record a benchmark run"),
    EndpointSpec("POST", "/api/models/{model_id}/admit", "admit a model"),
    EndpointSpec("POST", "/api/models/{model_id}/reject", "reject a model"),
    EndpointSpec("POST", "/api/models/{model_id}/quarantine", "quarantine a model"),
    EndpointSpec("GET", "/api/models/{model_id}/health", "fetch a model health profile"),
    EndpointSpec("POST", "/api/models/{model_id}/cancel", "cancel a model run or mark a model cancelled"),
    EndpointSpec("GET", "/api/hardware/profile", "fetch the local hardware profile"),
    EndpointSpec("POST", "/api/models/estimate", "estimate model resource requirements"),
    EndpointSpec("GET", "/api/model-routing/status", "report safe model routing status"),
    EndpointSpec("GET", "/api/version", "application version and readiness", review_required=False),
)


class EndpointInventory:
    def __init__(self, endpoints: tuple[EndpointSpec, ...] = REQUIRED_API_ENDPOINTS) -> None:
        self.endpoints = endpoints

    def required_paths(self) -> set[tuple[str, str]]:
        return {(endpoint.method, endpoint.path) for endpoint in self.endpoints}

    def as_dict(self) -> dict[str, Any]:
        return {
            "endpoint_count": len(self.endpoints),
            "endpoints": [endpoint.as_dict() for endpoint in self.endpoints],
        }

    def compare_to_registered(self, registered: set[tuple[str, str]]) -> dict[str, Any]:
        registered_methods = {method for method, _ in registered}
        required = {(method, path) for method, path in self.required_paths() if method in registered_methods}
        missing = sorted(required - registered)
        return {
            "status": "pass" if not missing else "fail",
            "missing": [{"method": method, "path": path} for method, path in missing],
            "extra": [],
            "required_count": len(self.endpoints),
            "registered_count": len(registered),
        }
